name: login_page
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.17.6 <3.0.0"


dev_dependencies:
  pedantic: ^1.9.2

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true